import assert from "node:assert/strict";
import { spawn, execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

// Real stdio server, real browser storage/clipboard/downloads; only neutral fixtures.
const root = fileURLToPath(new URL("../", import.meta.url));
const mcpRequire = createRequire(join(root, "packages/mcp/package.json"));
const webRequire = createRequire(join(root, "apps/web/package.json"));
const coreRequire = createRequire(join(root, "packages/core/package.json"));
const { Client } = mcpRequire("@modelcontextprotocol/sdk/client/index.js");
const { StdioClientTransport } = mcpRequire("@modelcontextprotocol/sdk/client/stdio.js");
const { unzipSync } = coreRequire("fflate");
const temporary = await mkdtemp(join(tmpdir(), "wedraft-web-smoke-"));
const evidence = join(root, "output/playwright/web-ai");
await mkdir(evidence, { recursive: true });
const cli = join(root, "packages/cli/dist/cli.mjs");
const report = { checks: [], errors: [], requestsOutsideApp: [], startedAt: new Date().toISOString() };
let browser; let vite;
const client = new Client({ name: "wedraft-web-smoke", version: "0.1.0" });
const waitFor = async (predicate) => {
  for (let i = 0; i < 80; i++) { if (await predicate()) return; await new Promise((done) => setTimeout(done, 100)); }
  throw new Error("Timed out waiting for state");
};
const check = (name) => { report.checks.push(name); console.log(`PASS ${name}`); };
try {
  for (const target of ["cli", "mcp"]) execFileSync(process.execPath, [join(root, "scripts/build-tools.mjs"), target], { cwd: root });
  const url = process.env.WEDRAFT_WEB_URL || "http://127.0.0.1:1435/";
  if (!process.env.WEDRAFT_WEB_URL) {
    const viteBin = join(dirname(webRequire.resolve("vite/package.json")), "bin/vite.js");
    vite = spawn(process.execPath, [viteBin, "--host", "127.0.0.1", "--port", "1435", "--strictPort"], { cwd: join(root, "apps/web"), stdio: "pipe" });
    let logs = "";
    vite.stderr.on("data", (data) => { logs += data; });
    await waitFor(async () => { if (vite.exitCode !== null) throw new Error(logs); try { return (await fetch(url)).ok; } catch { return false; } });
  }
  await client.connect(new StdioClientTransport({ command: process.execPath,
    args: [join(root, "packages/mcp/dist/server.mjs"), "--output-dir", temporary], stderr: "pipe" }));
  const png = await readFile(join(root, "apps/desktop/public/sample-editorial-image.png"));
  const original = "# AI 与网页共同编辑\r\n\r\n这段正文保留 **重点** 与 [原始来源](https://example.com/source)。\r\n\r\n## 1. 可以继续修改\r\n\r\n![内置示例](assets/sample.png \"图片来源：WeDraft 内置样图\")\r\n\r\n|项目|状态|\r\n|---|---|\r\n|文章包|可编辑|\r\n\r\n```js\r\nconst example = 1;\r\n```\r\n";
  const input = { markdown: original, templateId: "next-edition", assets: [{ path: "assets/sample.png", mimeType: "image/png", base64: png.toString("base64") }] };
  const exported = await client.callTool({ name: "export_article", arguments: input });
  assert.notEqual(exported.isError, true);
  assert.equal(exported.structuredContent.status, "ready");
  const bundle = exported.structuredContent.files.find((file) => file.endsWith(".zip"));
  assert.equal(new TextDecoder().decode(unzipSync(await readFile(bundle))["article.md"]), original);
  check("MCP exports exact source and local image to portable bundle");
  browser = await chromium.launch({ channel: "chrome", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ["clipboard-read", "clipboard-write"] });
  const page = await context.newPage();
  page.on("pageerror", (error) => report.errors.push(error.message));
  page.on("request", (request) => { if (!request.url().startsWith(url) && !/^(data:|blob:)/.test(request.url())) report.requestsOutsideApp.push(request.url()); });
  await page.goto(url);
  await page.getByRole("button", { name: "使用这篇示例" }).waitFor();
  await page.screenshot({ path: join(evidence, "desktop.png") });
  const importer = page.getByLabel("导入文章文件");
  const editor = page.locator(".markdown-editor");
  await importer.setInputFiles(bundle);
  await waitFor(async () => (await editor.inputValue()) === original.replaceAll("\r\n", "\n"));
  await waitFor(() => page.locator(".wechat-article img").evaluateAll((images) => images.length > 0 && images.every((image) => image.complete && image.naturalWidth > 0)));
  check("Web imports MCP bundle, template and decoded image");
  const changed = (await editor.inputValue()).replace("这段正文", "网页修订正文");
  await editor.fill(changed);
  await page.getByRole("button", { name: "撤回上一步", exact: true }).click();
  assert(!(await editor.inputValue()).includes("网页修订正文"));
  await page.getByRole("button", { name: "重做下一步", exact: true }).click();
  assert((await editor.inputValue()).includes("网页修订正文"));
  const paragraph = page.locator('[data-wedraft-edit-kind="paragraph"]').first();
  await paragraph.fill("从预览直接修改的正文。");
  await editor.click();
  await waitFor(async () => (await editor.inputValue()).includes("从预览直接修改的正文"));
  check("Textarea undo/redo and preview editing write back to Markdown");
  await page.getByRole("button", { name: "小哈公社", exact: true }).click();
  await editor.press("ControlOrMeta+End");
  await editor.press("End");
  await editor.press("Enter");
  await editor.press("Enter");
  await page.locator('input[type="file"]:not([aria-label="导入文章文件"])').setInputFiles(join(root, "apps/desktop/public/sample-editorial-image.png"));
  await page.getByPlaceholder("例如：新华社、品牌官网、作者拍摄").fill("测试作者拍摄");
  await page.getByRole("button", { name: "添加图片", exact: true }).click();
  await waitFor(async () => (await editor.inputValue()).includes("测试作者拍摄"));
  await page.getByRole("button", { name: "导出", exact: true }).click();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "可编辑文章包" }).click();
  const portablePath = join(evidence, "roundtrip.wedraft.zip");
  await (await downloaded).saveAs(portablePath);
  const source = await editor.inputValue();
  const archive = unzipSync(await readFile(portablePath));
  assert.equal(new TextDecoder().decode(archive["article.md"]), source);
  assert.equal(JSON.parse(new TextDecoder().decode(archive["manifest.json"])).templateId, "default-business");
  assert.equal(Object.keys(archive).filter((name) => name.startsWith("assets/")).length, 2);
  check("Local image/caption and template survive web bundle export");
  await page.getByRole("button", { name: "复制排版", exact: true }).click();
  if (await page.getByRole("button", { name: "确认并继续复制" }).isVisible()) await page.getByRole("button", { name: "确认并继续复制" }).click();
  await waitFor(async () => (await page.locator(".web-status").innerText()).includes("排版已复制"));
  const clipboard = await page.evaluate(async () => {
    const [item] = await navigator.clipboard.read();
    return { html: await (await item.getType("text/html")).text(), text: await (await item.getType("text/plain")).text() };
  });
  const cliOutput = join(temporary, "cli-roundtrip");
  const cliResult = JSON.parse(execFileSync(process.execPath, [cli, "render", "--input", portablePath, "--out", cliOutput], { encoding: "utf8" }));
  assert.equal(cliResult.status, "ready");
  assert.equal(clipboard.text, await readFile(join(cliOutput, "body.txt"), "utf8"));
  assert(clipboard.html.includes("data:image/png;base64,") && clipboard.html.includes("<table") && clipboard.html.includes("测试作者拍摄"));
  assert(!clipboard.text.includes("AI 与网页共同编辑"));
  const pastePage = await context.newPage();
  await pastePage.goto(url);
  await pastePage.evaluate(() => { const target = document.createElement("div"); target.id = "paste-check"; target.contentEditable = "true"; document.body.replaceChildren(target); });
  await pastePage.locator("#paste-check").focus();
  await pastePage.keyboard.press("ControlOrMeta+V");
  await waitFor(async () => (await pastePage.locator("#paste-check").innerText()).includes("测试作者拍摄"));
  assert.equal(await pastePage.locator("#paste-check img").count(), 2);
  await pastePage.close();
  check("Actual rich clipboard and browser paste preserve body, table, images and captions");
  await page.getByRole("button", { name: "本机草稿", exact: true }).click();
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await page.reload();
  await waitFor(async () => (await editor.inputValue()) === source);
  await importer.setInputFiles({ name: "invalid.wedraft.zip", mimeType: "application/zip", buffer: Buffer.from("not a zip") });
  await waitFor(async () => (await page.locator(".web-status.error").count()) > 0);
  assert.equal(await editor.inputValue(), source);
  check("IndexedDB reload and invalid-import recovery preserve current source");
  await editor.fill("缺图文章\n\n![图](missing.png)");
  await page.getByRole("button", { name: "复制排版", exact: true }).click();
  await page.getByRole("heading", { name: "修正后再复制" }).waitFor();
  assert.equal(await page.getByRole("button", { name: "确认并继续复制" }).count(), 0);
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await importer.setInputFiles(portablePath);
  await waitFor(async () => (await editor.inputValue()) === source);
  check("Blocking missing-image issue prevents copy; portable bundle restores editable draft");
  await page.screenshot({ path: join(evidence, "desktop-edited.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "阅读预览", exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  assert((await page.locator(".phone-shell").boundingBox()).width > 350);
  await page.screenshot({ path: join(evidence, "mobile.png") });
  check("390px screen keeps full reading width and reachable actions");
  assert.deepEqual(report.errors, []);
  assert.deepEqual(report.requestsOutsideApp, []);
  check("No page runtime errors or off-origin requests for the local fixture");
} finally {
  await writeFile(join(evidence, "smoke-report.json"), JSON.stringify(report, null, 2));
  await browser?.close(); await client.close(); vite?.kill();
  await rm(temporary, { recursive: true, force: true });
}
